version: '1'
name: bigdata
services:
  hadoop-namenode:
      image: apache/hadoop:3.3.6
      hostname: hadoop-namenode
      privileged: true
      environment:
        HADOOP_HOME: /opt/hadoop
      volumes:
        - $DATA_DIR/bigdata/hadoop/name:/data:rw
        - $CONFIG_DIR/bigdata/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
        - $CONFIG_DIR/bigdata/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
        - $HOME_DIR/compose/scripts/bigdata/start-hdfs.sh:/start-hdfs.sh     
      ports:
        - "9870:9870"
      command: ["/bin/bash", "/start-hdfs.sh"]
  
  hadoop-datanode1:
    image: apache/hadoop:3.3.6
    hostname: hadoop-datanode1
    privileged: true
    environment:
      HADOOP_HOME: /opt/hadoop
    volumes:
      - $DATA_DIR/bigdata/hadoop/data1:/data/:rw
      - $CONFIG_DIR/bigdata/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - $CONFIG_DIR/bigdata/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
    depends_on:
      - hadoop-namenode
    command: ["hdfs","datanode"]

  hadoop-datanode2:
    image: apache/hadoop:3.3.6
    hostname: hadoop-datanode2
    privileged: true
    environment:
      HADOOP_HOME: /opt/hadoop
    volumes:
      - $DATA_DIR/bigdata/hadoop/data2:/data/:rw
      - $CONFIG_DIR/bigdata/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - $CONFIG_DIR/bigdata/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
    depends_on:
      - hadoop-namenode
    command: ["hdfs","datanode"]

  hive-metastore:
    image: 'hive:my-hive'
    privileged: true
    build:
      context: "../dockerfiles/"
      dockerfile: "hive-dockerfile"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver 
                      -Djavax.jdo.option.ConnectionURL=jdbc:mysql://${HIVE_METASTORE_HOST}:${HIVE_METASTORE_PORT}/${HIVE_METASTORE_DB}?createDatabaseIfNotExist=true
                      -Djavax.jdo.option.ConnectionUserName=${HIVE_METASTORE_USER} 
                      -Djavax.jdo.option.ConnectionPassword=${HIVE_METASTORE_PASSWORD}"
    ports:
      - "9083:9083"

  hive-hiveserver2:
    image: 'hive:my-hive'
    privileged: true
    build:
      context: "../dockerfiles/"
      dockerfile: "hive-dockerfile"
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Ddfs.permissions=false -Dhive.metastore.uris=thrift://hive-metastore:9083"
      IS_RESUME: "true"
    volumes:
      - $CONFIG_DIR/bigdata/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - hive-metastore
      - hadoop-namenode

networks:
  default:
     external:
       name: ${DOCKER_NETWORK_NAME}