version: '1'
name: flink
services:
  jobmanager:
    image: "flink:my-flink"
    build:
      context: "../dockerfiles/"
      dockerfile: "flink-dockerfile"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager    
      
  taskmanager:
    image: "flink:my-flink"
    build:
      context: "../dockerfiles/"
      dockerfile: "flink-dockerfile"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10    
      
networks:
  default:
    external: true
    name: ${DOCKER_NETWORK_NAME}